import Head from "next/head";
import Image from "next/image";
// import styles from "../styles/Home.module.css";
import Main from "../Components/Main/Main";
import Shops from "../Components/Main/Shops";
import JoinAndDiscover from "../Components/Main/JoinAndDiscover";
import Footer from "../Components/Footer/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main />
      <Shops />
      <JoinAndDiscover />
      <Footer />
    </div>
  );
}
